version: "3.8"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hertz-front
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    networks:
      - hertz-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: hertz-nginx-front
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app
    networks:
      - hertz-network
    restart: unless-stopped

networks:
  hertz-network:
    driver: bridge
